name: Kogito Google Chrome extension tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'

      - name: Unzip extension
        run: unzip tmp/chrome_extension_kogito_kie_editors_0.4.2.zip

      - name: Start Xvfb
        if: matrix.os == 'ubuntu-latest'
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Install project
        run: npm install

      - name: Run tests
        env:
          DISPLAY: ":99.0"
          UNZIPPED_CHROME_EXTENSION_PATH: ${{ github.workspace }}/dist
        run: npm test

      - name: Archive png screenshot
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: screenshots-${{ matrix.os }}
          path: screenshots
          
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: logs-${{ matrix.os }}
          path: logs