name: Kogito Google Chrome extension tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Install project
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        run: npm ci
        run: npm test
